### ISSUE TITLE
After clicking "Tain" a non ending Training loop starts.

### ISSUE THREAD

**Issue by shahzaibpl** [clofus/clofus-chatbot#5]
Shows this error after some time:
`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/shahzaib/Desktop/clofus rasa/clofus-chatbot/clofusbot/rasa.py", line 14, in <module>
    from rasa_core.channels.console import ConsoleInputChannel
ImportError: cannot import name 'ConsoleInputChannel'

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
     killed: false,
     code: 1,
     signal: null,
     cmd: '\n                        python3 -m clofusbot.rasa train-nlu PLPS_BOT\n                        python3 -m clofusbot.rasa train-dialogue PLPS_BOT\n                        ' },
  isOperational: true,
  killed: false,
  code: 1,
  signal: null,
  cmd: '\n                        python3 -m clofusbot.rasa train-nlu PLPS_BOT\n                        python3 -m clofusbot.rasa train-dialogue PLPS_BOT\n                        ' }
`

**Comment by karthikbalu** [comment]
This could be killed by the operating system more than this repo code

**Comment by shahzaibpl** [comment]
Kindly elaborate on what can I do to resolve this issue. Plus Kindly mention which rasa version needed to run this project. As ConsoleInputChannel is depreciated in Rasa.

**Comment by shahzaibpl** [comment]
@karthikbalu  I appreciate your quick response. Kindly elaborate on what can I do to resolve this issue. Plus Kindly mention which rasa version needed to run this project. As ConsoleInputChannel is depreciated in Rasa.

**Comment by karthikbalu** [comment]
Pls contact me at karthikbalu.meng@gmail.com
